In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import tensorflow as tf
import keras

Using TensorFlow backend.


In [3]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
Y = iris.target
print(X.shape)
print(Y.shape)

(150, 4)
(150,)


In [4]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
Y_1hot = enc.fit_transform(Y.reshape(-1, 1)).toarray()
print(Y[0], " -- one hot enocding --> ", Y_1hot[0])
print(Y[50], " -- one hot enocding --> ", Y_1hot[50])
print(Y[100], " -- one hot enocding --> ", Y_1hot[100])

0  -- one hot enocding -->  [1. 0. 0.]
1  -- one hot enocding -->  [0. 1. 0.]
2  -- one hot enocding -->  [0. 0. 1.]


In [12]:
from keras.backend import tensorflow_backend as K
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
K.set_session(tf.Session(config=config))

from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))

print(keras.__version__)
from keras import backend as K
K.tensorflow_backend._get_available_gpus()

2.1.2


['/job:localhost/replica:0/task:0/device:GPU:0',
 '/job:localhost/replica:0/task:0/device:GPU:1']

In [6]:
from keras.utils.training_utils import multi_gpu_model
model = multi_gpu_model(model, gpus=2)

In [7]:
model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
dense_1_input (InputLayer)      (None, 4)            0                                            
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 4)            0           dense_1_input[0][0]              
__________________________________________________________________________________________________
lambda_2 (Lambda)               (None, 4)            0           dense_1_input[0][0]              
__________________________________________________________________________________________________
sequential_1 (Sequential)       (None, 3)            35          lambda_1[0][0]                   
                                                                 lambda_2[0][0]                   
__________

In [8]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y_1hot, epochs=1000, batch_size=1024)

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
Use tf.cast instead.
Epoch 1/1000
150/150 [==============================] - 1s 5ms/step - loss: 1.2532 - acc: 0.3333
Epoch 2/1000
150/150 [==============================] - 0s 31us/step - loss: 1.2411 - acc: 0.3333
Epoch 3/1000
150/150 [==============================] - 0s 28us/step - loss: 1.2291 - acc: 0.3333
Epoch 4/1000
150/150 [==============================] - 0s 26us/step - loss: 1.2173 - acc: 0.3333
Epoch 5/1000
150/150 [==============================] - 0s 26us/step - loss: 1.2056 - acc: 0.3333
Epoch 6/1000
150/150 [==============================] - 0s 25us/step - loss: 1.1940 - acc: 0.3333
Epoch 7/1000
150/150 [==============================] - 0s 27us/step - loss: 1.1826 - acc: 0.3333
Epoch 8/1000
150/150 [==============================] - 0s 26us/step - loss: 1.1714 - acc: 0.3333
Epoch 9/1000
150/150 [==============================] - 0s 25us/step - loss: 1.1603 - acc: 0.333

Epoch 78/1000
150/150 [==============================] - 0s 26us/step - loss: 0.7242 - acc: 0.5133
Epoch 79/1000
150/150 [==============================] - 0s 28us/step - loss: 0.7206 - acc: 0.5133
Epoch 80/1000
150/150 [==============================] - 0s 26us/step - loss: 0.7170 - acc: 0.5133
Epoch 81/1000
150/150 [==============================] - 0s 28us/step - loss: 0.7135 - acc: 0.5133
Epoch 82/1000
150/150 [==============================] - 0s 28us/step - loss: 0.7100 - acc: 0.5133
Epoch 83/1000
150/150 [==============================] - 0s 28us/step - loss: 0.7065 - acc: 0.5133
Epoch 84/1000
150/150 [==============================] - 0s 29us/step - loss: 0.7031 - acc: 0.5133
Epoch 85/1000
150/150 [==============================] - 0s 29us/step - loss: 0.6997 - acc: 0.5133
Epoch 86/1000
150/150 [==============================] - 0s 28us/step - loss: 0.6964 - acc: 0.5133
Epoch 87/1000
150/150 [==============================] - 0s 26us/step - loss: 0.6931 - acc: 0.5133
Epoch 88/1

150/150 [==============================] - 0s 26us/step - loss: 0.5297 - acc: 0.9267
Epoch 161/1000
150/150 [==============================] - 0s 25us/step - loss: 0.5282 - acc: 0.9267
Epoch 162/1000
150/150 [==============================] - 0s 28us/step - loss: 0.5268 - acc: 0.9267
Epoch 163/1000
150/150 [==============================] - 0s 27us/step - loss: 0.5253 - acc: 0.9267
Epoch 164/1000
150/150 [==============================] - 0s 27us/step - loss: 0.5239 - acc: 0.9267
Epoch 165/1000
150/150 [==============================] - 0s 26us/step - loss: 0.5225 - acc: 0.9333
Epoch 166/1000
150/150 [==============================] - 0s 26us/step - loss: 0.5211 - acc: 0.9333
Epoch 167/1000
150/150 [==============================] - 0s 27us/step - loss: 0.5197 - acc: 0.9333
Epoch 168/1000
150/150 [==============================] - 0s 26us/step - loss: 0.5184 - acc: 0.9333
Epoch 169/1000
150/150 [==============================] - 0s 30us/step - loss: 0.5170 - acc: 0.9333
Epoch 170/1000


150/150 [==============================] - 0s 28us/step - loss: 0.4429 - acc: 0.9533
Epoch 243/1000
150/150 [==============================] - 0s 28us/step - loss: 0.4421 - acc: 0.9533
Epoch 244/1000
150/150 [==============================] - 0s 28us/step - loss: 0.4413 - acc: 0.9533
Epoch 245/1000
150/150 [==============================] - 0s 31us/step - loss: 0.4405 - acc: 0.9533
Epoch 246/1000
150/150 [==============================] - 0s 31us/step - loss: 0.4398 - acc: 0.9533
Epoch 247/1000
150/150 [==============================] - 0s 28us/step - loss: 0.4390 - acc: 0.9533
Epoch 248/1000
150/150 [==============================] - 0s 27us/step - loss: 0.4382 - acc: 0.9533
Epoch 249/1000
150/150 [==============================] - 0s 27us/step - loss: 0.4375 - acc: 0.9533
Epoch 250/1000
150/150 [==============================] - 0s 27us/step - loss: 0.4367 - acc: 0.9533
Epoch 251/1000
150/150 [==============================] - 0s 28us/step - loss: 0.4360 - acc: 0.9533
Epoch 252/1000


150/150 [==============================] - 0s 26us/step - loss: 0.3912 - acc: 0.9533
Epoch 325/1000
150/150 [==============================] - 0s 25us/step - loss: 0.3906 - acc: 0.9533
Epoch 326/1000
150/150 [==============================] - 0s 30us/step - loss: 0.3901 - acc: 0.9533
Epoch 327/1000
150/150 [==============================] - 0s 27us/step - loss: 0.3896 - acc: 0.9533
Epoch 328/1000
150/150 [==============================] - 0s 27us/step - loss: 0.3891 - acc: 0.9533
Epoch 329/1000
150/150 [==============================] - 0s 26us/step - loss: 0.3886 - acc: 0.9533
Epoch 330/1000
150/150 [==============================] - 0s 25us/step - loss: 0.3881 - acc: 0.9533
Epoch 331/1000
150/150 [==============================] - 0s 28us/step - loss: 0.3876 - acc: 0.9533
Epoch 332/1000
150/150 [==============================] - 0s 28us/step - loss: 0.3870 - acc: 0.9533
Epoch 333/1000
150/150 [==============================] - 0s 25us/step - loss: 0.3865 - acc: 0.9533
Epoch 334/1000


150/150 [==============================] - 0s 27us/step - loss: 0.3528 - acc: 0.9667
Epoch 407/1000
150/150 [==============================] - 0s 30us/step - loss: 0.3524 - acc: 0.9667
Epoch 408/1000
150/150 [==============================] - 0s 30us/step - loss: 0.3520 - acc: 0.9667
Epoch 409/1000
150/150 [==============================] - 0s 29us/step - loss: 0.3515 - acc: 0.9667
Epoch 410/1000
150/150 [==============================] - 0s 27us/step - loss: 0.3511 - acc: 0.9667
Epoch 411/1000
150/150 [==============================] - 0s 28us/step - loss: 0.3507 - acc: 0.9667
Epoch 412/1000
150/150 [==============================] - 0s 30us/step - loss: 0.3503 - acc: 0.9667
Epoch 413/1000
150/150 [==============================] - 0s 31us/step - loss: 0.3498 - acc: 0.9667
Epoch 414/1000
150/150 [==============================] - 0s 29us/step - loss: 0.3494 - acc: 0.9667
Epoch 415/1000
150/150 [==============================] - 0s 27us/step - loss: 0.3490 - acc: 0.9667
Epoch 416/1000


150/150 [==============================] - 0s 25us/step - loss: 0.3195 - acc: 0.9800
Epoch 489/1000
150/150 [==============================] - 0s 25us/step - loss: 0.3191 - acc: 0.9800
Epoch 490/1000
150/150 [==============================] - 0s 24us/step - loss: 0.3188 - acc: 0.9800
Epoch 491/1000
150/150 [==============================] - 0s 27us/step - loss: 0.3184 - acc: 0.9800
Epoch 492/1000
150/150 [==============================] - 0s 26us/step - loss: 0.3180 - acc: 0.9800
Epoch 493/1000
150/150 [==============================] - 0s 25us/step - loss: 0.3176 - acc: 0.9800
Epoch 494/1000
150/150 [==============================] - 0s 24us/step - loss: 0.3172 - acc: 0.9800
Epoch 495/1000
150/150 [==============================] - 0s 29us/step - loss: 0.3168 - acc: 0.9800
Epoch 496/1000
150/150 [==============================] - 0s 26us/step - loss: 0.3164 - acc: 0.9800
Epoch 497/1000
150/150 [==============================] - 0s 28us/step - loss: 0.3161 - acc: 0.9800
Epoch 498/1000


150/150 [==============================] - 0s 24us/step - loss: 0.2890 - acc: 0.9800
Epoch 571/1000
150/150 [==============================] - 0s 27us/step - loss: 0.2886 - acc: 0.9800
Epoch 572/1000
150/150 [==============================] - 0s 24us/step - loss: 0.2883 - acc: 0.9800
Epoch 573/1000
150/150 [==============================] - 0s 25us/step - loss: 0.2879 - acc: 0.9800
Epoch 574/1000
150/150 [==============================] - 0s 25us/step - loss: 0.2876 - acc: 0.9800
Epoch 575/1000
150/150 [==============================] - 0s 26us/step - loss: 0.2872 - acc: 0.9800
Epoch 576/1000
150/150 [==============================] - 0s 27us/step - loss: 0.2868 - acc: 0.9800
Epoch 577/1000
150/150 [==============================] - 0s 27us/step - loss: 0.2865 - acc: 0.9800
Epoch 578/1000
150/150 [==============================] - 0s 27us/step - loss: 0.2861 - acc: 0.9800
Epoch 579/1000
150/150 [==============================] - 0s 27us/step - loss: 0.2858 - acc: 0.9800
Epoch 580/1000


150/150 [==============================] - 0s 23us/step - loss: 0.2607 - acc: 0.9800
Epoch 653/1000
150/150 [==============================] - 0s 23us/step - loss: 0.2604 - acc: 0.9800
Epoch 654/1000
150/150 [==============================] - 0s 23us/step - loss: 0.2601 - acc: 0.9800
Epoch 655/1000
150/150 [==============================] - 0s 28us/step - loss: 0.2597 - acc: 0.9800
Epoch 656/1000
150/150 [==============================] - 0s 25us/step - loss: 0.2594 - acc: 0.9800
Epoch 657/1000
150/150 [==============================] - 0s 25us/step - loss: 0.2591 - acc: 0.9800
Epoch 658/1000
150/150 [==============================] - 0s 25us/step - loss: 0.2587 - acc: 0.9800
Epoch 659/1000
150/150 [==============================] - 0s 25us/step - loss: 0.2584 - acc: 0.9800
Epoch 660/1000
150/150 [==============================] - 0s 25us/step - loss: 0.2581 - acc: 0.9800
Epoch 661/1000
150/150 [==============================] - 0s 26us/step - loss: 0.2578 - acc: 0.9800
Epoch 662/1000


150/150 [==============================] - 0s 23us/step - loss: 0.2348 - acc: 0.9800
Epoch 735/1000
150/150 [==============================] - 0s 27us/step - loss: 0.2345 - acc: 0.9800
Epoch 736/1000
150/150 [==============================] - 0s 27us/step - loss: 0.2342 - acc: 0.9800
Epoch 737/1000
150/150 [==============================] - 0s 25us/step - loss: 0.2339 - acc: 0.9800
Epoch 738/1000
150/150 [==============================] - 0s 29us/step - loss: 0.2336 - acc: 0.9800
Epoch 739/1000
150/150 [==============================] - 0s 26us/step - loss: 0.2333 - acc: 0.9800
Epoch 740/1000
150/150 [==============================] - 0s 24us/step - loss: 0.2330 - acc: 0.9800
Epoch 741/1000
150/150 [==============================] - 0s 27us/step - loss: 0.2327 - acc: 0.9800
Epoch 742/1000
150/150 [==============================] - 0s 27us/step - loss: 0.2324 - acc: 0.9800
Epoch 743/1000
150/150 [==============================] - 0s 27us/step - loss: 0.2321 - acc: 0.9800
Epoch 744/1000


150/150 [==============================] - 0s 29us/step - loss: 0.2116 - acc: 0.9800
Epoch 817/1000
150/150 [==============================] - 0s 27us/step - loss: 0.2113 - acc: 0.9800
Epoch 818/1000
150/150 [==============================] - 0s 28us/step - loss: 0.2110 - acc: 0.9800
Epoch 819/1000
150/150 [==============================] - 0s 25us/step - loss: 0.2108 - acc: 0.9800
Epoch 820/1000
150/150 [==============================] - 0s 27us/step - loss: 0.2105 - acc: 0.9800
Epoch 821/1000
150/150 [==============================] - 0s 28us/step - loss: 0.2102 - acc: 0.9800
Epoch 822/1000
150/150 [==============================] - 0s 26us/step - loss: 0.2100 - acc: 0.9800
Epoch 823/1000
150/150 [==============================] - 0s 27us/step - loss: 0.2097 - acc: 0.9800
Epoch 824/1000
150/150 [==============================] - 0s 28us/step - loss: 0.2094 - acc: 0.9800
Epoch 825/1000
150/150 [==============================] - 0s 25us/step - loss: 0.2092 - acc: 0.9800
Epoch 826/1000


150/150 [==============================] - 0s 27us/step - loss: 0.1910 - acc: 0.9800
Epoch 899/1000
150/150 [==============================] - 0s 24us/step - loss: 0.1908 - acc: 0.9800
Epoch 900/1000
150/150 [==============================] - 0s 25us/step - loss: 0.1905 - acc: 0.9800
Epoch 901/1000
150/150 [==============================] - 0s 23us/step - loss: 0.1903 - acc: 0.9800
Epoch 902/1000
150/150 [==============================] - 0s 26us/step - loss: 0.1901 - acc: 0.9800
Epoch 903/1000
150/150 [==============================] - 0s 24us/step - loss: 0.1898 - acc: 0.9800
Epoch 904/1000
150/150 [==============================] - 0s 28us/step - loss: 0.1896 - acc: 0.9800
Epoch 905/1000
150/150 [==============================] - 0s 25us/step - loss: 0.1894 - acc: 0.9800
Epoch 906/1000
150/150 [==============================] - 0s 24us/step - loss: 0.1891 - acc: 0.9800
Epoch 907/1000
150/150 [==============================] - 0s 26us/step - loss: 0.1889 - acc: 0.9800
Epoch 908/1000


150/150 [==============================] - 0s 27us/step - loss: 0.1731 - acc: 0.9800
Epoch 981/1000
150/150 [==============================] - 0s 28us/step - loss: 0.1729 - acc: 0.9800
Epoch 982/1000
150/150 [==============================] - 0s 23us/step - loss: 0.1727 - acc: 0.9800
Epoch 983/1000
150/150 [==============================] - 0s 28us/step - loss: 0.1725 - acc: 0.9800
Epoch 984/1000
150/150 [==============================] - 0s 28us/step - loss: 0.1723 - acc: 0.9800
Epoch 985/1000
150/150 [==============================] - 0s 27us/step - loss: 0.1721 - acc: 0.9800
Epoch 986/1000
150/150 [==============================] - 0s 27us/step - loss: 0.1719 - acc: 0.9800
Epoch 987/1000
150/150 [==============================] - 0s 27us/step - loss: 0.1717 - acc: 0.9800
Epoch 988/1000
150/150 [==============================] - 0s 27us/step - loss: 0.1715 - acc: 0.9800
Epoch 989/1000
150/150 [==============================] - 0s 27us/step - loss: 0.1713 - acc: 0.9800
Epoch 990/1000


In [9]:
Y_pred = model.predict(X)

In [10]:
import numpy as np
Y_pred2 = np.argmax(Y_pred, axis=1)
for i in range(np.shape(Y_pred)[0]):
    print('{} ---> {} '.format(Y_pred[i], Y_pred2[i]))

[9.783442e-01 2.165527e-02 4.775344e-07] ---> 0 
[9.6363139e-01 3.6366224e-02 2.3971916e-06] ---> 0 
[9.7213149e-01 2.7867084e-02 1.3622295e-06] ---> 0 
[9.6165985e-01 3.8336895e-02 3.1650459e-06] ---> 0 
[9.7788322e-01 2.2116344e-02 4.8199303e-07] ---> 0 
[9.7871208e-01 2.1287557e-02 3.7902720e-07] ---> 0 
[9.7153193e-01 2.8466523e-02 1.5336758e-06] ---> 0 
[9.7627354e-01 2.3725711e-02 7.1123009e-07] ---> 0 
[9.5535886e-01 4.4635348e-02 5.7786033e-06] ---> 0 
[9.6918744e-01 3.0811140e-02 1.4244390e-06] ---> 0 
[9.8189569e-01 1.8104006e-02 2.3042286e-07] ---> 0 
[9.7174895e-01 2.8249901e-02 1.1911941e-06] ---> 0 
[9.6947473e-01 3.0523634e-02 1.6187978e-06] ---> 0 
[9.6604109e-01 3.3956431e-02 2.5486108e-06] ---> 0 
[9.8690456e-01 1.3095269e-02 5.9000843e-08] ---> 0 
[9.867393e-01 1.326064e-02 6.857326e-08] ---> 0 
[9.8309374e-01 1.6906062e-02 2.0999630e-07] ---> 0 
[9.7813326e-01 2.1866113e-02 5.7585714e-07] ---> 0 
[9.8010844e-01 1.9891374e-02 2.4762662e-07] ---> 0 
[9.7945797e-01 2.0

In [11]:
print('Misclassified Samples:', (Y != Y_pred2).sum())

Misclassified Samples: 3
